"""Token hashing helper.

Only the hash is ever stored; the plaintext is generated by the caller
(CLI or test) and passed in, never persisted.
"""

from __future__ import annotations

import hashlib


def hash_token(token: str) -> str:
    """Return the SHA-256 hex digest of *token*."""
    return hashlib.sha256(token.encode()).hexdigest()
